name: Test Load

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Install uv and set the python version
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        uv venv
        source .venv/bin/activate
        uv sync --group dev

    - name: Load Plugin
      run: |
        python -c "
        import nonebot;
        from nonebot.adapters.onebot.v11 import Adapter;
        nonebot.init();
        nonebot.get_driver().register_adapter(Adapter);
        nonebot.load_from_toml('pyproject.toml');
        assert nonebot.get_plugin_by_module_name('nonebot_plugin_vocu') is not None;
        "
